# statefulset.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foo-statefulset
spec:
  selector:
    matchLabels:
      app: foo
  serviceName: "foo-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: foo
          image: springio/springboot-foo
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "hostpath"
        resources:
          requests:
            storage: 1Gi
