apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am foo!
  labels:
    by: kustomization
  name: foo-service-v1
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    by: kustomization
    type: demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am foo!
  labels:
    by: kustomization
    type: demo
  name: foo-deployment-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      by: kustomization
      type: demo
  template:
    metadata:
      annotations:
        note: Hello, I am foo!
      labels:
        by: kustomization
        type: demo
    spec:
      containers:
      - image: springio/springboot-foo
        name: api-service
        ports:
        - containerPort: 8080
