# simple/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    type: demo
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP