apiVersion: v1
kind: Namespace
metadata:
  annotations:
    note: Hello, I am production!
  labels:
    app: prod-foo
    type: prod-demo
  name: production-namespace
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    note: Hello, I am production!
  labels:
    app: prod-foo
    by: kustomization
    type: prod-demo
  name: prod-foo-service-v1
  namespace: production-namespace
spec:
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 8080
  selector:
    app: prod-foo
    by: kustomization
    type: prod-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    note: Hello, I am production!
  labels:
    app: prod-foo
    by: kustomization
    type: prod-demo
  name: prod-the-prod-development
  namespace: production-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-foo
      by: kustomization
      type: prod-demo
  template:
    metadata:
      annotations:
        note: Hello, I am production!
      labels:
        app: prod-foo
        by: kustomization
        type: prod-demo
    spec:
      containers:
      - image: springio/springboot-foo
        name: the-prod-container
        ports:
        - containerPort: 8080
