# emptydir-memory.yaml
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-memory-pod
spec:
  volumes:
    - name: html
      emptyDir:
        medium: Memory    #指定使用記憶體儲存
        sizeLimit: 256Mi  #限制記憶體大小
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
    - name: alpine
      image: alpine
      volumeMounts:
        - mountPath: /html
          name: html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          echo $(hostname) $(date) >> /html/index.html
          sleep 10;
          done